name: sqlite-for-data-scientists

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.8.5
  - pip==20.2.2
  - tqdm==4.48.2
  - jupyter==1.0.0
  - pandas==1.1.0
  - tqdm==4.48.2

  - pip:
    - ipython-sql==0.4.0
    - datasette==0.48
    - sqlitebiter==0.34.0
    - sqlite-utils==3.0.0